// Copyright 2017-2024 @polkadot/x-global authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/x-global', path: 'auto', type: 'auto', version: '12.6.3-4-x' };
