checks:
  argument-count:
    config:
      threshold: 5
  method-complexity:
    config:
      threshold: 7
  method-count:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 30

exclude_patterns:
- "**/*.spec.js"
- "**/*.spec.ts"
- "packages/networks/src/substrate.ts"
- "packages/util/src/is/utf8.ts"
- "packages/x-noble-hashes/src/**.ts"
- "packages/x-noble-secp256k1/src/**.ts"
