// Copyright 2017-2023 @polkadot/x-crypto authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/x-crypto', path: 'auto', type: 'auto', version: '11.1.3-1-x' };
