// Copyright 2017-2025 @polkadot/x-bundle authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/x-bundle', path: 'auto', type: 'auto', version: '13.5.6-0-x' };
