// Copyright 2017-2021 @polkadot/networks authors & contributors
// SPDX-License-Identifier: Apache-2.0

import fs from 'fs';

import { isString } from '@polkadot/util';

import { SUBSTRATE_REGISTRY } from '../src/constants';

async function getSubstrateRegistry () {
  const original = await fetch(SUBSTRATE_REGISTRY);
  const json = original.json();

  return json.registry
    .map((e) =>
      Object
        .entries(e)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([k, v]) => `    ${k}: ${isString(v) ? `'${v}'` : v}`)
        .join(',\n')
        .map((e) => `\n  {\n${e}\n  }`)
    )
    .join('\n');
}

getSubstrateRegistry()
  .then((entries) => {
    fs.writeFileSync('../src/knownSubstrate.ts', `// Copyright 2017-2021 @polkadot/networks authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by scripts/fromSubstrate.mjs
//
// Do not edit, rather
//   - make a PR to the upstream registry as per https://raw.githubusercontent.com/paritytech/substrate/master/ss58-registry.json
//   - yarn build:networks
//

import type { KnownSubstrate } from './types';

export const knownSubstrate: KnownSubstrate[] = [${entries}];
`);

    process.exit(0);
  })
  .catch((error) => {
    console.error(error);

    process.exit(-1);
  });
