// Copyright 2017-2021 @polkadot/x-noble-secp256k1 authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@polkadot/x-noble-secp256k1', version: '8.1.3-9' };
