// Copyright 2017-2024 @polkadot/util-crypto authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev
// (packageInfo imports will be kept as-is, user-editable)

import { packageInfo as netInfo } from '@polkadot/networks/packageInfo';
import { detectPackage } from '@polkadot/util';
import { packageInfo as utilInfo } from '@polkadot/util/packageInfo';
import { packageInfo as randomInfo } from '@polkadot/x-randomvalues';

import { packageInfo } from './packageInfo.js';

detectPackage(packageInfo, null, [netInfo, randomInfo, utilInfo]);
